name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Test
        run: deno task ok

      - name: Build
        run: deno task build

      - name: Readme
        run: |
          deno task readme
          git diff --quiet --exit-code || (echo "Run 'deno task readme'." && exit 1)
